<a href="https://colab.research.google.com/github/Unalunapark/practice/blob/main/%EB%94%B4%EC%A7%93/5_1_%EB%94%B4%EC%A7%93_%EC%9E%91%EC%97%85%ED%98%952_%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 신용카드서비스를 떠나는 고객을 찾아라
- 나이, 급여, 결혼 상태, 신용 카드 한도, 신용 카드 카테고리 등의 컬럼이 있음
- 평가: ROC-AUC, 정확도(Accuracy), F1, 정밀도(Precision), 재현율(Recall)을 구하시오
- target : Attrition_Flag (1:이탈, 0:유지)
- csv파일 생성 : 수험번호.csv (예시 아래 참조)
~~~
CLIENTNUM,Attrition_Flag
788544108,0.633
719356008,0.123
712142733,0.355
~~~


### 평가(분류)
~~~
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# 정확도
print(accuracy_score(y_test, pred))

# 정밀도
print(precision_score(y_test, pred))

# 재현율 (민감도)
print(recall_score(y_test, pred))

# F1
print(f1_score(y_test , pred))

# roc-auc
print(roc_auc_score(y_test, pred_proba))
~~~

## 데이터 불러오기

In [16]:
import pandas as pd
train=pd.read_csv("/content/drive/MyDrive/데이터모음/딴짓/ceredit card/train.csv")
test=pd.read_csv("/content/drive/MyDrive/데이터모음/딴짓/ceredit card/test.csv")

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
train.head()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,...,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Attrition_Flag
0,778461408,38,M,1,High School,Married,$80K - $120K,Blue,23,4,...,2,22149.0,987,21162.0,1.633,2409,36,0.800,0.045,0
1,718263108,44,F,3,Unknown,Divorced,Less than $40K,Blue,32,3,...,2,1693.0,1457,236.0,0.919,2829,42,0.615,0.861,1
2,780384483,49,M,4,Unknown,Unknown,$80K - $120K,Blue,39,2,...,2,2886.0,925,1961.0,0.946,5481,58,0.758,0.321,1
3,719592483,43,F,5,Graduate,Single,Unknown,Blue,34,6,...,3,4607.0,2440,2167.0,0.646,4825,77,0.878,0.530,0
4,771453033,47,M,3,High School,Married,$60K - $80K,Blue,35,5,...,2,17343.0,1280,16063.0,1.314,3170,57,0.629,0.074,0

In [6]:
test.head()

,CLIENTNUM,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,788544108,43,F,2,High School,Single,Less than $40K,Blue,37,4,3,0,6611.0,1041,5570.0,0.744,4037,74,0.682,0.157
1,719356008,39,F,3,Graduate,Single,Less than $40K,Blue,36,4,3,4,1438.3,0,1438.3,1.022,4548,69,0.917,0.000
2,712142733,37,F,3,Post-Graduate,Married,Less than $40K,Blue,26,5,3,2,1910.0,1164,746.0,0.744,2028,39,1.053,0.609
3,789394833,47,M,2,Unknown,Divorced,$80K - $120K,Blue,37,1,2,2,21714.0,1969,19745.0,0.944,13270,104,0.625,0.091
4,742778358,44,M,1,Graduate,Single,$60K - $80K,Blue,37,3,1,4,16739.0,1229,15510.0,0.497,4014,69,0.568,0.073

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8101 entries, 0 to 8100
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 8101 non-null   int64
 1   Customer_Age              8101 non-null   int64
 2   Gender                    8101 non-null   object
 3   Dependent_count           8101 non-null   int64
 4   Education_Level           8101 non-null   object
 5   Marital_Status            8101 non-null   object
 6   Income_Category           8101 non-null   object
 7   Card_Category             8101 non-null   object
 8   Months_on_book            8101 non-null   int64
 9   Total_Relationship_Count  8101 non-null   int64
 10  Months_Inactive_12_mon    8101 non-null   int64
 11  Contacts_Count_12_mon     8101 non-null   int64
 12  Credit_Limit              8101 non-null   float64
 13  Total_Revolving_Bal       8101 non-null   int64
 14  Avg_Open_To_Buy           8101 non-null   float64
 15  Total_Amt_Chng_Q4_Q1      8101 non-null   float64
 16  Total_Trans_Amt           8101 non-null   int64
 17  Total_Trans_Ct            8101 non-null   int64
 18  Total_Ct_Chng_Q4_Q1       8101 non-null   float64
 19  Avg_Utilization_Ratio     8101 non-null   float64
 20  Attrition_Flag            8101 non-null   int64
dtypes: float64(5), int64(11), object(5)
memory usage: 1.3+ MB

In [8]:
train['Attrition_Flag'].value_counts()
#0    6815 데이터 불균형
#1    1286

0    6815
1    1286
Name: Attrition_Flag, dtype: int64

In [9]:
train.isnull().sum().sum()

0

In [10]:
test.isnull().sum().sum()

0

## 데이터 전처리 & 피처엔지니어링

##1.베이스라인모델만들기
#object type 5개 제거
#1
cols=train.select_dtypes(include='object').columns
print(cols)
#2
train=train.drop(cols, axis=1)
#3
train.drop(cols, axis=1, inplace=True)
#4
train=train.select_dtypes(exclude='object')
print(train.info())
test=test.select_dtypes(exclude='object')
print(test.info)
#label

#one-hot

In [38]:
import pandas as pd
#베이스라인
train=pd.read_csv("/content/drive/MyDrive/데이터모음/딴짓/ceredit card/train.csv")
test=pd.read_csv("/content/drive/MyDrive/데이터모음/딴짓/ceredit card/test.csv")
print(train.shape, test.shape)
train=train.select_dtypes(exclude='object')
test=test.select_dtypes(exclude='object')
print(train.shape, test.shape)

(8101, 21) (2026, 20)
(8101, 16) (2026, 15)

In [39]:
#CLIENTNUM 삭제
train=train.drop('CLIENTNUM', axis=1)
testid=test.pop('CLIENTNUM')
print(train.shape, test.shape)

(8101, 15) (2026, 14)

In [40]:
train.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Attrition_Flag
0,38,1,23,4,3,2,22149.0,987,21162.0,1.633,2409,36,0.800,0.045,0
1,44,3,32,3,3,2,1693.0,1457,236.0,0.919,2829,42,0.615,0.861,1
2,49,4,39,2,2,2,2886.0,925,1961.0,0.946,5481,58,0.758,0.321,1
3,43,5,34,6,6,3,4607.0,2440,2167.0,0.646,4825,77,0.878,0.530,0
4,47,3,35,5,1,2,17343.0,1280,16063.0,1.314,3170,57,0.629,0.074,0

In [41]:
test.head()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,43,2,37,4,3,0,6611.0,1041,5570.0,0.744,4037,74,0.682,0.157
1,39,3,36,4,3,4,1438.3,0,1438.3,1.022,4548,69,0.917,0.000
2,37,3,26,5,3,2,1910.0,1164,746.0,0.744,2028,39,1.053,0.609
3,47,2,37,1,2,2,21714.0,1969,19745.0,0.944,13270,104,0.625,0.091
4,44,1,37,3,1,4,16739.0,1229,15510.0,0.497,4014,69,0.568,0.073

In [42]:
testid

0       788544108
1       719356008
2       712142733
3       789394833
4       742778358
          ...
2021    787361583
2022    713474733
2023    708486033
2024    717683583
2025    712887633
Name: CLIENTNUM, Length: 2026, dtype: int64

## 검증 데이터 분리

In [43]:
from sklearn.model_selection import train_test_split

# xtr, xval, ytr, yval = train_test_split(train, target, test_size, random_state)
xtr, xval, ytr, yval = train_test_split(train.drop('Attrition_Flag', axis=1), train['Attrition_Flag'], test_size=0.1, random_state=2022)

In [44]:
xtr.shape, xval.shape, ytr.shape, yval.shape

((7290, 14), (811, 14), (7290,), (811,))

In [45]:
xtr.head()
#CLIENTNUM 데이터 분리전에 삭제하기

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
3400,52,3,44,4,1,3,3416.0,2044,1372.0,0.994,1924,48,0.920,0.598
1550,34,1,36,6,2,3,3735.0,1285,2450.0,1.034,1877,33,1.200,0.344
5327,44,4,40,4,3,2,14370.0,945,13425.0,0.557,4510,79,0.646,0.066
826,44,2,35,2,3,4,4196.0,561,3635.0,0.741,2558,38,0.652,0.134
4520,55,2,47,5,3,2,3096.0,2217,879.0,0.799,2011,41,0.783,0.716

## 모델 & 평가
-모델불러오기, fit학습, 예측predict

In [46]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(xtr,ytr) #학습
pred=model.predict(xval) #예측

In [47]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
import sklearn.metrics
dir(sklearn.metrics)

## ! dir(sklearn.metrics)

```
import sklearn.metrics
dir(sklearn.metrics)
```

['ConfusionMatrixDisplay',
 'DetCurveDisplay',
 'DistanceMetric',
 'PrecisionRecallDisplay',
 'PredictionErrorDisplay',
 'RocCurveDisplay',
 'SCORERS',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_classification',
 '_dist_metrics',
 '_pairwise_distances_reduction',
 '_pairwise_fast',
 '_plot',
 '_ranking',
 '_regression',
 '_scorer',
 'accuracy_score',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'auc',
 'average_precision_score',
 'balanced_accuracy_score',
 'brier_score_loss',
 'calinski_harabasz_score',
 'check_scoring',
 'class_likelihood_ratios',
 'classification_report',
 'cluster',
 'cohen_kappa_score',
 'completeness_score',
 'confusion_matrix',
 'consensus_score',
 'coverage_error',
 'd2_absolute_error_score',
 'd2_pinball_score',
 'd2_tweedie_score',
 'davies_bouldin_score',
 'dcg_score',
 'det_curve',
 'euclidean_distances',
 'explained_variance_score',
 'f1_score',
 'fbeta_score',
 'fowlkes_mallows_score',
 'get_scorer',
 'get_scorer_names',
 'hamming_loss',
 'hinge_loss',
 'homogeneity_completeness_v_measure',
 'homogeneity_score',
 'jaccard_score',
 'label_ranking_average_precision_score',
 'label_ranking_loss',
 'log_loss',
 'make_scorer',
 'matthews_corrcoef',
 'max_error',
 'mean_absolute_error',
 'mean_absolute_percentage_error',
 'mean_gamma_deviance',
 'mean_pinball_loss',
 'mean_poisson_deviance',
 'mean_squared_error',
 'mean_squared_log_error',
 'mean_tweedie_deviance',
 'median_absolute_error',
 'multilabel_confusion_matrix',
 'mutual_info_score',
 'nan_euclidean_distances',
 'ndcg_score',
 'normalized_mutual_info_score',
 'pair_confusion_matrix',
 'pairwise',
 'pairwise_distances',
 'pairwise_distances_argmin',
 'pairwise_distances_argmin_min',
 'pairwise_distances_chunked',
 'pairwise_kernels',
 'precision_recall_curve',
 'precision_recall_fscore_support',
 'precision_score',
 'r2_score',
 'rand_score',
 'recall_score',
 'roc_auc_score',
 'roc_curve',
 'silhouette_samples',
 'silhouette_score',
 'top_k_accuracy_score',
 'v_measure_score',
 'zero_one_loss']

In [48]:
#예측한 결과값을 자체적으로 평가하기
import sklearn.metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
dir(sklearn.metrics)

# 정확도
print(accuracy_score(yval, pred))

# 정밀도
print(precision_score(yval, pred))

# 재현율 (민감도)
print(recall_score(yval, pred))

# F1
print(f1_score(yval , pred))

0.967940813810111
0.9279279279279279
0.8512396694214877
0.8879310344827588

In [ ]:


# roc-auc
print(roc_auc_score(y_test, pred_proba))

## 예측 및 csv 제출

##정리

In [ ]:
# 아래 코드는 실제 시험에서는 확인할 수 없는 부분입니다.
# y_test = pd.read_csv("y_test.csv")
# print(roc_auc_score(y_test, pred[:,1]))